kafka:
  bootstrapServersConfig: 'localhost:9092'
  schemaRegistryUrlConfig: 'http://localhost:8081'

  topics:
    balanceAuthorization: 'balance-authorization'
    balance: 'balance'

  stateStores:
    balance: 'balanceState'
