server:
  port: 5054

kafka:
  bootstrapServersConfig: 'broker:29092'
  schemaRegistryUrlConfig: 'http://schema-registry:8081'

  topics:
    balanceAuthorization: 'balance-authorization'
    balance: 'balance'

  stateStores:
    balance: 'balance-state'
