kafka:
  bootstrapServersConfig: 'localhost:9092'
  schemaRegistryUrlConfig: 'http://localhost:8081'

  topics:
    preferencesAuthorization: 'preferences-authorization'
    preferences: 'preferences'
    balanceAuthorization: 'balance-authorization'

  stateStores:
    preferences: 'preferences-state'
