server:
  port: 5053

kafka:
  bootstrapServersConfig: 'broker:29092'
  schemaRegistryUrlConfig: 'http://schema-registry:8081'

  topics:
    preferencesAuthorization: 'preferences-authorization'
    preferences: 'preferences'
    balanceAuthorization: 'balance-authorization'

  stateStores:
    preferences: 'preferences-state'
