server:
  port: 5051

metrics:
  jvmMetrics: true
  jmx:
    enabled: true
  prometheusCollection: true

kafka:
  bootstrapServersConfig: 'broker:29092'
  schemaRegistryUrlConfig: 'http://schema-registry:8081'

  topics:
    preferencesAuthorization: 'preferences-authorization'
