kafka:
  bootstrapServersConfig: 'localhost:9092'

  topics:
    preferencesAuthorization: 'preferences-authorization'
    preferences: 'preferences'
    balanceAuthorization: 'balance-authorization'
