{
 "title": "HTTP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Command Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{domain=\"piggybox\",job=\"command-service\"}"
    }
   ]
  },
  {
   "title": "Query Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{domain=\"piggybox\",job=\"query-service\"}"
    }
   ]
  },
  {
   "title": "Median",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_preferences_create_post_requests{quantile=\"0.5\",job=\"command-service\"}",
     "legendFormat": "Create Preferences"
    },
    {
     "expr": "api_preferences_changeCountry_post_requests{quantile=\"0.5\",job=\"command-service\"}",
     "legendFormat": "Change Country"
    },
    {
     "expr": "api_balance_addFunds_post_requests{quantile=\"0.5\",job=\"command-service\"}",
     "legendFormat": "Add Funds"
    },
    {
     "expr": "api_balance_withdrawFunds_post_requests{quantile=\"0.5\",job=\"command-service\"}",
     "legendFormat": "Withdraw Funds"
    },
    {
     "expr": "api_customers_getPreferences_get_requests{quantile=\"0.5\",job=\"query-service\"}",
     "legendFormat": "Get Preferences"
    },
    {
     "expr": "api_customers_getBalance_get_requests{quantile=\"0.5\",job=\"query-service\"}",
     "legendFormat": "Get Balance"
    },
    {
     "expr": "api_customers_getHistory_get_requests{quantile=\"0.5\",job=\"query-service\"}",
     "legendFormat": "Get History"
    }
   ]
  },
  {
   "title": "Preferences Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{domain=\"piggybox\",job=\"preferences-service\"}"
    }
   ]
  },
  {
   "title": "Balance Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{domain=\"piggybox\",job=\"balance-service\"}"
    }
   ]
  },
  {
   "title": "99.9% percentile",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_preferences_create_post_requests{quantile=\"0.999\",job=\"command-service\"}",
     "legendFormat": "Create Preferences"
    },
    {
     "expr": "api_preferences_changeCountry_post_requests{quantile=\"0.999\",job=\"command-service\"}",
     "legendFormat": "Change Country"
    },
    {
     "expr": "api_balance_addFunds_post_requests{quantile=\"0.999\",job=\"command-service\"}",
     "legendFormat": "Add Funds"
    },
    {
     "expr": "api_balance_withdrawFunds_post_requests{quantile=\"0.999\",job=\"command-service\"}",
     "legendFormat": "Withdraw Funds"
    },
    {
     "expr": "api_customers_getPreferences_get_requests{quantile=\"0.999\",job=\"query-service\"}",
     "legendFormat": "Get Preferences"
    },
    {
     "expr": "api_customers_getBalance_get_requests{quantile=\"0.999\",job=\"query-service\"}",
     "legendFormat": "Get Balance"
    },
    {
     "expr": "api_customers_getHistory_get_requests{quantile=\"0.999\",job=\"query-service\"}",
     "legendFormat": "Get History"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(_2xx_responses[1m])", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(api_preferences_create_post_requests_count{job=\"command-service\"}[1m])",
     "legendFormat": "Create Preferences"
    },
    {
     "expr": "rate(api_preferences_changeCountry_post_requests_count{job=\"command-service\"}[1m])",
     "legendFormat": "Change Country"
    },
    {
     "expr": "rate(api_balance_addFunds_post_requests_count{job=\"command-service\"}[1m])",
     "legendFormat": "Add Funds"
    },
    {
     "expr": "rate(api_balance_withdrawFunds_post_requests_count{job=\"command-service\"}[1m])",
     "legendFormat": "Withdraw Funds"
    },
    {
     "expr": "rate(api_customers_getPreferences_get_requests_count{job=\"query-service\"}[1m])",
     "legendFormat": "Get Preferences"
    },
    {
     "expr": "rate(api_customers_getBalance_get_requests_count{job=\"query-service\"}[1m])",
     "legendFormat": "Get Balance"
    },
    {
     "expr": "rate(api_customers_getHistory_get_requests_count{job=\"query-service\"}[1m])",
     "legendFormat": "Get History"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(_4xx_responses[1m])", "legendFormat": "{{job}}" }
   ]
  }
 ]
}