{
 "title": "JVM",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(total_used{domain=\"piggybox\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(total_used{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "heap_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "heap_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "heap_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "non_heap_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "non_heap_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "total_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "total_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "total_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_load{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(PS_Scavenge_count{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "PS Scavenge"
    },
    {
     "expr": "rate(PS_MarkSweep_count{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "PS MarkSweep"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "daemon_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "deadlock_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "deadlock"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_load{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "GC Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(PS_Scavenge_time{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "PS Scavenge"
    },
    {
     "expr": "increase(PS_MarkSweep_time{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "PS MarkSweep"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "new_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "new"
    },
    {
     "expr": "runnable_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "runnable"
    },
    {
     "expr": "blocked_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "waiting_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "waiting"
    },
    {
     "expr": "timed_waiting_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "timed_waiting"
    },
    {
     "expr": "terminated_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "terminated"
    }
   ]
  },
  { "title": "Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Eden",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_PS_Eden_Space_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "pools_PS_Eden_Space_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "pools_PS_Eden_Space_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Survivor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_PS_Survivor_Space_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "pools_PS_Survivor_Space_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "pools_PS_Survivor_Space_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Old Generation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_PS_Old_Gen_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "pools_PS_Old_Gen_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "pools_PS_Old_Gen_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_Metaspace_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "pools_Metaspace_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "pools_Metaspace_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Compressed Class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_Compressed_Class_Space_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "pools_Compressed_Class_Space_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "pools_Compressed_Class_Space_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_Code_Cache_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "pools_Code_Cache_committed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "pools_Code_Cache_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}